---
apiVersion: v1
kind: Service
metadata:
  name: {{ project_slug }}
  namespace: dge
spec:
  type: ClusterIP
  selector:
    app: {{ project_slug }}
  ports:
    - protocol: TCP
      port: {{ server_port }}
      targetPort: {{ server_port }}
