name: PR build & test

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, edited, synchronize ]

jobs:
  build_test:
    name: Build & test
    strategy:
      matrix:
        os: [ self-hosted-ubuntu-2004 ]
        java-version: [ 17 ]
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java-version }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: /home/runner/.m2/repository
          key: ${{ runner.os }}-m2repo-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2repo

      - name: Formatting check
        run: mvn -B spotless:check

      - name: Build & test
        run: mvn -B clean verify
