name: "Trivy"

on:
  workflow_dispatch:
  schedule:
    - cron: '20 5 * * 1-5'
jobs:
  trivy:
    name: Run Trivy Scanner
    strategy:
      matrix:
        os: [ self-hosted-ubuntu-2204 ]
    runs-on: {{ "${{ matrix.os }}" }}
    env:
      repo_name: "IMGARENA/{{ project_slug }}"
      image_name: "imgarena/streams/{{ project_slug }}"

    steps:
      - name: Setup oras
        uses: oras-project/setup-oras@v1

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Download and extract the vulnerability DB
        run: |
          mkdir -p $GITHUB_WORKSPACE/.cache/trivy/db
          oras pull ghcr.io/aquasecurity/trivy-db:2
          tar -xzf db.tar.gz -C $GITHUB_WORKSPACE/.cache/trivy/db
          rm db.tar.gz

      - name: Download and extract the Java DB
        run: |
          mkdir -p $GITHUB_WORKSPACE/.cache/trivy/java-db
          oras pull ghcr.io/aquasecurity/trivy-java-db:1
          tar -xzf javadb.tar.gz -C $GITHUB_WORKSPACE/.cache/trivy/java-db
          rm javadb.tar.gz

      - name: Cache DBs
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}/.cache/trivy
          key: cache-trivy-${{ steps.date.outputs.date }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: 724428741115

      - name: Set environment variables
        run: echo "ecr_registry={{ "${{ steps.login-ecr.outputs.registry }}" }}/{{ "${{ env.image_name }}" }}" >> $GITHUB_ENV

      - name: Get latest release
        uses: rez0n/actions-github-release@main
        id: latest_release
        env:
          token: {{ "${{ secrets.ACTION_GITHUB_TOKEN }}" }}
          repository: {{ "${{ env.repo_name }}" }}
          type: "stable"

      - name: Remove 'v' from version
        run: |
          version={{ "${{ steps.latest_release.outputs.release }}" }}
          echo "version={{ "${version#v}" }}" >> $GITHUB_ENV

      - name: Get latest docker images
        run: docker pull {{ "${{ env.ecr_registry }}" }}:{{ "${{ env.version }}" }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '{{ "${{ env.ecr_registry }}" }}:{{ "${{ env.version }}" }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: '10m'
        env:
          TRIVY_SKIP_DB_UPDATE: true
          TRIVY_SKIP_JAVA_DB_UPDATE: true

      - name: Send Slack notification
        if: {{ "${{ failure() }}" }}
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_ICON: 'https://www.freeiconspng.com/uploads/face-png-2.png'
          SLACK_USERNAME: 'Spartacus'
          SLACK_CHANNEL: 'tech_streams'
          SLACK_WEBHOOK: {{ "${{ secrets.SLACK_WEBHOOK_URL }}" }}
          SLACK_COLOR: '#FF0000'
          MSG_MINIMAL: true
          SLACK_MESSAGE: "Spartans gather! :military_helmet:\n:alert:Enemy vulnerabilities have been found in {{ "${{ env.repo_name }}" }}\n See https://github.com/{{ "${{ env.repo_name }}" }}/actions/runs/{{ "${{github.run_id}}" }}"
